create table author
(
    id   int4 generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

create table body_type
(
    id   int4 generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

create table brand
(
    id   int4 generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

create table car
(
    id          int4 generated by default as identity,
    description varchar(255) not null,
    bodyType_id int4         not null references body_type (id),
    brand_id    int4         not null references brand (id),
    primary key (id)
);

create table Advertisement
(
    id        int4 generated by default as identity,
    created   timestamp        default now(),
    is_sold   boolean not null default false,
    author_id int4    not null references author (id),
    car_id    int4    not null references car (id),
    primary key (id)
)
